DeploymentStaging/deployPackage/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Tradesman_Still_Working__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to enable if Tradesman are still working? Enables when Tradesman starts work.</description>
        <label>Tradesman Still Working?</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

DeploymentStaging/deployPackage/objects/HOG_Maintenance_Servicing_Form__c.object
<CustomObject>
</CustomObject>

DeploymentStaging/deployPackage/objects/Work_Order_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_Text__c</fullName>
        <description>List of names of assigned tradesman, populated by trigger on work_Order_Activity_Assignment__c object</description>
        <label>Assigned To</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Assigned_Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned Vendor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Work Order Activities</relationshipLabel>
        <relationshipName>Work_Order_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Description_of_Equipment__c</fullName>
        <formula>BLANKVALUE( 
Equipment__r.Description_of_Equipment__c, 
Maintenance_Work_Order__r.Equipment__r.Description_of_Equipment__c 
)</formula>
        <label>Description of Equipment</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Name__c</fullName>
        <description>&quot;Smart Location Name&quot; - show activity location name if specified, otherwise show Work Order Location name</description>
        <formula>BLANKVALUE( Location__r.Name ,  Maintenance_Work_Order__r.Location__r.Name )</formula>
        <label>Location Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Work Order Activities</relationshipLabel>
        <relationshipName>Work_Order_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Maintenance_Work_Order__c</fullName>
        <label>Maintenance Work Order</label>
        <referenceTo>HOG_Maintenance_Servicing_Form__c</referenceTo>
        <relationshipLabel>Work Order Activities</relationshipLabel>
        <relationshipName>Work_Order_Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Scheduled_Finish_Date__c</fullName>
        <label>Scheduled Finish Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Scheduled_Start_Date__c</fullName>
        <label>Scheduled Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status_Reason__c</fullName>
        <label>Status Reason</label>
        <picklist>
            <controllingField>Status__c</controllingField>
            <picklistValues>
                <fullName>Waiting on parts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting on information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting on repairs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pulled off activity</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Started at Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finished at Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finished for the day</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Work_Center__c</fullName>
        <label>Work Center</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <label>Work Order Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Order Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Work_Order_Activity_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Rejected__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Rejected</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tradesman__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tradesman</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Work Order Activity Assignments</relationshipLabel>
        <relationshipName>Work_Order_Activity_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Order_Activity__c</fullName>
        <label>Work Order Activity</label>
        <referenceTo>Work_Order_Activity__c</referenceTo>
        <relationshipLabel>Assigned Tradesmen</relationshipLabel>
        <relationshipName>Work_Order_Activity_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Work Order Activity Assignment</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Order Activity Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DeploymentStaging/deployPackage/classes/POC_VTTM_ActivityListController.cls
public without sharing class POC_VTTM_ActivityListController {

	public List<Work_Order_Activity__c> assignedActivities   {get; private set;}
	public List<Work_Order_Activity__c> allActivities   {get; private set;}
	private Set<Id> assignedActivityIds;

	public Contact Tradesman {get; private set;}
	public Boolean IsAdmin {get;private set;}
    public Boolean IsVendorSupervisor {get;private set;}

    //Browser Variables
    public Boolean isMobileDevice {get; private set;}
    public Boolean isGeolocationAvailable {get; private set;}
    private Decimal tradesmanLatitude;
    private Decimal tradesmanLongitude;

	public POC_VTTM_ActivityListController() {

		Tradesman = VTT_Utilities.LoadTradesmanInfo();
		IsAdmin = VTT_Utilities.IsAdminUser();   
        IsVendorSupervisor =  VTT_Utilities.IsVendorSupervisor();

        assignedActivities = [
				select Id, Name, Assigned_Vendor__c, Description__c, 
				Work_Center__c, Assigned_Text__c, Location_Name__c,
				Maintenance_Work_Order__r.User_Status_Code__c, 
				Maintenance_Work_Order__r.Work_Order_Priority_Number__c, 
				Maintenance_Work_Order__r.Order_Type__c, 
				Maintenance_Work_Order__r.Name, 
				Maintenance_Work_Order__r.Location__r.Name,
				Maintenance_Work_Order__r.Location__r.Route__r.Route_Number__c, 
				Maintenance_Work_Order__r.Plant_Section__c,
				Maintenance_Work_Order__r.Order_Description__c,
				Maintenance_Work_Order__r.Description_of_Equipment__c,
				Maintenance_Work_Order__r.Required_End_Date__c,
				Maintenance_Work_Order__r.Location__c,
				Scheduled_Start_Date__c,
				Scheduled_Finish_Date__c,
				Status__c, 
				Status_Reason__c 
				from Work_Order_Activity__c 
				where 
				id in (select Work_Order_Activity__c from Work_Order_Activity_Assignment__c where Rejected__c <> true and Tradesman__c =  :tradesman.ID)
				And Status__c != :VTT_Utilities.ACTIVITY_STATUS_COMPLETED
				order by Scheduled_Start_Date__c
				Limit 1000
			];

		assignedActivityIds = new Set<Id>();
		for(Work_Order_Activity__c activity : assignedActivities) {
			assignedActivityIds.add(activity.Id);
		}

        if(IsAdmin) {
        	allActivities = [select Id, Name, Assigned_Vendor__c, Description__c, 
				Work_Center__c, Assigned_Text__c, Location_Name__c, 
				Maintenance_Work_Order__r.User_Status_Code__c, 
				Maintenance_Work_Order__r.Work_Order_Priority_Number__c, 
				Maintenance_Work_Order__r.Order_Type__c, 
				Maintenance_Work_Order__r.Name, 
				Maintenance_Work_Order__r.Location__r.Name,
				Maintenance_Work_Order__r.Location__r.Route__r.Route_Number__c,
				Maintenance_Work_Order__r.Plant_Section__c,
				Maintenance_Work_Order__r.Order_Description__c,
				Maintenance_Work_Order__r.Description_of_Equipment__c,
				Maintenance_Work_Order__r.Required_End_Date__c,
				Maintenance_Work_Order__r.Location__c,
				Scheduled_Start_Date__c,
				Scheduled_Finish_Date__c,
				Status__c, 
				Status_Reason__c 
				from Work_Order_Activity__c
				Where Id Not In :assignedActivityIds
				order by Scheduled_Start_Date__c
				Limit 1000];
        } else if (IsVendorSupervisor) {
        	allActivities = [select Id, Name, Assigned_Vendor__c, Description__c, 
				Work_Center__c, Assigned_Text__c, Location_Name__c,
				Maintenance_Work_Order__r.User_Status_Code__c, 
				Maintenance_Work_Order__r.Work_Order_Priority_Number__c, 
				Maintenance_Work_Order__r.Order_Type__c, 
				Maintenance_Work_Order__r.Name, 
				Maintenance_Work_Order__r.Location__r.Name,
				Maintenance_Work_Order__r.Location__r.Route__r.Route_Number__c, 
				Maintenance_Work_Order__r.Plant_Section__c,
				Maintenance_Work_Order__r.Order_Description__c,
				Maintenance_Work_Order__r.Description_of_Equipment__c,
				Maintenance_Work_Order__r.Required_End_Date__c,
				Maintenance_Work_Order__r.Location__c,
				Scheduled_Start_Date__c,
				Scheduled_Finish_Date__c,
				Status__c, 
				Status_Reason__c 
				from Work_Order_Activity__c
				where Assigned_Vendor__c = :Tradesman.AccountId
				And Id Not In :assignedActivityIds
				order by Scheduled_Start_Date__c
				Limit 1000];
        }
	}

	public PageReference StartWork()
    {
        Tradesman.Tradesman_Status__c = VTT_Utilities.TRADESMAN_STATUS_STARTEDWORK;
        Tradesman.Tradesman_Status_Date__c = Datetime.now();

        try {
            update Tradesman;
        } catch(DmlException ex) {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'Cannot start work: ' + ex.getMessage()));
            return null;
        } finally {
            Tradesman = VTT_Utilities.LoadTradesmanInfo();
        }

        return null;
    }

    public Boolean GetCanStartWork()
    {
        return Tradesman.Current_Work_Order_Activity__c == null && 
        Tradesman.Tradesman_Status__c != VTT_Utilities.Tradesman_Status_StartedWork &&
        Tradesman.Tradesman_Still_Working__c == false;
    }

    //Functions for setting Browser variables
    public void SetIsMobileDevice() {
        String isMobileDeviceParam = ApexPages.currentPage().getParameters().get('isMobileDevice');
        isMobileDevice = (isMobileDeviceParam == 'true') ? true : false;
        System.debug('isMobileDevice: ' + isMobileDevice);
        System.debug('isGeolocationAvailable: ' + isGeolocationAvailable + ' latitude: ' + tradesmanLatitude + ' longitude: ' + tradesmanLongitude);
    }

    public void SetGeolocation() {
    	String lat = ApexPages.currentPage().getParameters().get('latitude');
    	String longt = ApexPages.currentPage().getParameters().get('longitude');
        tradesmanLatitude = (lat!= null) ? Decimal.valueOf(lat) : null;
        tradesmanLongitude = (longt != null) ? Decimal.valueOf(longt) : null;
        isGeolocationAvailable = true;
        System.debug('isMobileDevice: ' + isMobileDevice);
        System.debug('isGeolocationAvailable: ' + isGeolocationAvailable + ' latitude: ' + tradesmanLatitude + ' longitude: ' + tradesmanLongitude);
    }
}