DeploymentStaging/deployPackage/objects/HOG_EOJ__c.object
<CustomObject>
    <description>End Of Job Report for DEFT</description>
    <fields>
        <fullName>Field_Operator1_Email__c</fullName>
        <label>Field Operator 1 Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Field_Operator2_Email__c</fullName>
        <label>Field Operator 2 Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Field_Operator3_Email__c</fullName>
        <label>Field Operator 3 Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Field_Operator4_Email__c</fullName>
        <label>Field Operator 4 Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Field_Senior_Email__c</fullName>
        <label>Field Senior Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Operations_Coordinator_Email__c</fullName>
        <label>Operations Coordinator Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Production_Coordinator_Email__c</fullName>
        <label>Production Coordinator Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Production_Engineer_Email__c</fullName>
        <label>Production Engineer Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <formula>Service_Rig_Program__r.Operator_Route__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Route</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Rig_Coordinator_Email__c</fullName>
        <label>Service Rig Coordinator Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Service_Rig_Planner_Email__c</fullName>
        <label>Service Rig Planner Email</label>
        <type>Email</type>
    </fields>
    <label>End of Job Report</label>
    <nameField>
        <displayFormat>EOJ-{0000000000}</displayFormat>
        <label>EOJ Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>End of Job Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DeploymentStaging/deployPackage/objects/HOG_Service_Rig_Program__c.object
<CustomObject>
    <description>An encapsulating object for Service Rig Prgram information needed for an approval process to begin work on a a Service Rig.</description>
    <fields>
        <fullName>Service_Rig_Planner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Rig Planner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Standard HOG - Administrator, Standard HOG - General User, System Administrator</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Service_Rig_Programs6</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Rig Program</label>
    <nameField>
        <displayFormat>SRP-{0000000000}</displayFormat>
        <label>Service Rig Program Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Rig Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DeploymentStaging/testClasses/classes/DEFT_UtilitiesTest.cls
@isTest
private class DEFT_UtilitiesTest {
	
	@isTest static void TestTriggerBeforeInsertEOJ() {
		User runningUser = DEFT_TestData.createDeftUser();
		User productionCoordinator = DEFT_TestData.createProductionCoordinator();
		User serviceRigCoordinator = DEFT_TestData.createServiceRigCoordinator();
		User serviceRigPlanner = DEFT_TestData.createServiceRigPlanner();

		System.runAs(runningUser) {
			Route__c route = RouteTestData.createRoute('Test Route');
			route.Operator_1_User__c = runningUser.Id;
			route.Operator_2_User__c = runningUser.Id;
			route.Operator_3_User__c = runningUser.Id;
			route.Operator_4_User__c = runningUser.Id;
			insert route;

			HOG_Service_Rig_Program__c serviceRigProgram = DEFT_TestData.createServiceRigProgram(runningUser, productionCoordinator, serviceRigCoordinator);
			serviceRigProgram.Service_Rig_Planner__c = serviceRigPlanner.Id;
			update serviceRigProgram;

			HOG_EOJ__c eoj = DEFT_TestData.createEOJReport(serviceRigProgram);

			//Test Email Fields
			eoj = [Select Id, Name, Production_Engineer_Email__c, Field_Operator1_Email__c, Field_Operator2_Email__c,
					Field_Operator3_Email__c, Field_Operator4_Email__c, Field_Senior_Email__c, Production_Coordinator_Email__c,
					Operations_Coordinator_Email__c, Service_Rig_Coordinator_Email__c, Service_Rig_Planner_Email__c
				   From HOG_EOJ__c
				   Where Id =: eoj.Id];
			System.assert(eoj.Production_Engineer_Email__c.equalsIgnoreCase(runningUser.Email));
			System.assert(eoj.Field_Operator1_Email__c.equalsIgnoreCase(runningUser.Email));
			System.assert(eoj.Field_Operator2_Email__c.equalsIgnoreCase(runningUser.Email));
			System.assert(eoj.Field_Operator3_Email__c.equalsIgnoreCase(runningUser.Email));
			System.assert(eoj.Field_Operator4_Email__c.equalsIgnoreCase(runningUser.Email));
			System.assert(eoj.Field_Senior_Email__c.equalsIgnoreCase(runningUser.Email));
			System.assert(eoj.Production_Coordinator_Email__c.equalsIgnoreCase(productionCoordinator.Email));
			System.assert(eoj.Operations_Coordinator_Email__c.equalsIgnoreCase(runningUser.Email));
			System.assert(eoj.Service_Rig_Coordinator_Email__c.equalsIgnoreCase(serviceRigCoordinator.Email));
			System.assert(eoj.Service_Rig_Planner_Email__c.equalsIgnoreCase(serviceRigPlanner.Email));
		}
	}
}