DeploymentStaging/deployPackage/objects/HOG_EOJ__c.object
<CustomObject>
    <description>End Of Job Report for DEFT</description>
    <fields>
        <fullName>Field_Operator1_Email__c</fullName>
        <label>Field Operator 1 Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Field_Operator2_Email__c</fullName>
        <label>Field Operator 2 Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Field_Operator3_Email__c</fullName>
        <label>Field Operator 3 Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Field_Operator4_Email__c</fullName>
        <label>Field Operator 4 Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Field_Senior_Email__c</fullName>
        <label>Field Senior Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Operations_Coordinator_Email__c</fullName>
        <label>Operations Coordinator Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Production_Coordinator_Email__c</fullName>
        <label>Production Coordinator Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Production_Engineer_Email__c</fullName>
        <label>Production Engineer Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Service_Rig_Coordinator_Email__c</fullName>
        <label>Service Rig Coordinator Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Service_Rig_Planner_Email__c</fullName>
        <label>Service Rig Planner Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Service_Rig_Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Service Rig Program</label>
        <referenceTo>HOG_Service_Rig_Program__c</referenceTo>
        <relationshipLabel>End of Job Reports</relationshipLabel>
        <relationshipName>EOJs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>End of Job Report</label>
    <nameField>
        <displayFormat>EOJ-{0000000000}</displayFormat>
        <label>EOJ Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>End of Job Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DeploymentStaging/deployPackage/objects/HOG_Service_Rig_Program__c.object
<CustomObject>
    <description>An encapsulating object for Service Rig Prgram information needed for an approval process to begin work on a a Service Rig.</description>
    <fields>
        <fullName>Field_Senior__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Field Senior</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Service_Rig_Programs4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Operations_Coordinator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Operations Coordinator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Service_Rig_Programs5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Production_Coordinator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Production coordinator whose financial approval is required for Approval.</description>
        <inlineHelpText>Set this as the user who can grant financial approval to this Service Rig Program.</inlineHelpText>
        <label>Production Coordinator</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserRole.DeveloperName</field>
                <operation>equals</operation>
                <value>Production_Coordinators</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Service_Rig_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Production_Engineer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Production Engineer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Service_Rig_Programs3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Route_Operator_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route Operator 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Service_Rig_Programs7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Route_Operator_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route Operator 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Service_Rig_Programs8</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Route_Operator_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route Operator 3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Service_Rig_Programs9</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Route_Operator_4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route Operator 4</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Service_Rig_Programs6rHW</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Rig_Coordinator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User who can grant technical approval for the Service Rig Program.</description>
        <inlineHelpText>Set this to an User who can grant Technical Approval for the Service Rig Program.</inlineHelpText>
        <label>Service Rig Coordinator</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserRole.DeveloperName</field>
                <operation>equals</operation>
                <value>Service_Rig_Coordinator</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Service_Rig_Programs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Rig_Planner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Rig Planner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Standard HOG - Administrator, Standard HOG - General User, System Administrator</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Service_Rig_Programs6</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Rig Program</label>
    <nameField>
        <displayFormat>SRP-{0000000000}</displayFormat>
        <label>Service Rig Program Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Rig Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DeploymentStaging/deployPackage/classes/DEFT_Utilities.cls
/*-------------------------------------------------------------------------------------------------
Author     : Shreyas Dhond
Company    : Husky Energy
Description: A Global Utility class for Downhole Equipment Failure Tracking
Inputs     : N/A
Test Class : DEFT_UtilitiesTest
History    : 05.05.16 ssd: Initial revision - End of Job Insert Trigger Handler (Populate Email Fields)         
---------------------------------------------------------------------------------------------------*/ 
global without sharing class DEFT_Utilities {
	
	//End of Job Status'
	public final static String EOJ_STATUS_NEW = 'New';
	public final static String EOJ_STATUS_SUBMITTED = 'Submitted';

	//Flag for trigger execution
	public static Boolean executeTriggerCode = true;

	//Permission Set Names
	public final static String SNR_PERMISSIONSET_NAME = 'HOG_SNR_User';
	public final static String SRP_PERMISSIONSET_NAME = 'HOG_Service_Rig_Program_Read_Write';

	/**************************************** Trigger Handlers *************************************/
	public static void TriggerBeforeInsertEOJ(final List<HOG_EOJ__c> pEndOfJobList) {
		System.debug('TriggerBeforeInsertEOJ');
		if(executeTriggerCode) {
			PopulateEOJEmailFieldsFromRigProgram(pEndOfJobList);
		}
	}

	/**************************************** Utility Functions ************************************/
	//Copy email fields for workflows on creation from Service Rig Programs
	public static void PopulateEOJEmailFieldsFromRigProgram(final List<HOG_EOJ__c> pEndOfJobList) {
		Set<Id> serviceRigProgramIds = new Set<Id>();
		Map<Id, HOG_Service_Rig_Program__c> rigProgramMap = new Map<Id, HOG_Service_Rig_Program__c>();


		//Create map of Service Rig Programs
		for(HOG_EOJ__c endOfJob : pEndOfJobList) {
			serviceRigProgramIds.add(endOfJob.Service_Rig_Program__c);
		}
		rigProgramMap = new Map<Id, HOG_Service_Rig_Program__c>([Select Id, Production_Engineer__r.Email, 
																	Route_Operator_1__r.Email,
																	Route_Operator_2__r.Email, 
																	Route_Operator_3__r.Email,
																	Route_Operator_4__r.Email, 
																	Field_Senior__r.Email, 
																	Production_Coordinator__r.Email, 
																	Operations_Coordinator__r.Email,
																	Service_Rig_Coordinator__r.Email,
																	Service_Rig_Planner__r.Email
																   From HOG_Service_Rig_Program__c
																   Where Id In :serviceRigProgramIds]);



		for(HOG_EOJ__c endOfJob : pEndOfJobList) {
			HOG_Service_Rig_Program__c rigProgram = rigProgramMap.get(endOfJob.Service_Rig_Program__c);
			endOfJob.Production_Engineer_Email__c = rigProgram.Production_Engineer__r.Email;
			endOfJob.Field_Operator1_Email__c = rigProgram.Route_Operator_1__r.Email;
			endOfJob.Field_Operator2_Email__c = rigProgram.Route_Operator_1__r.Email;
			endOfJob.Field_Operator3_Email__c = rigProgram.Route_Operator_1__r.Email;
			endOfJob.Field_Operator4_Email__c = rigProgram.Route_Operator_1__r.Email;
			endOfJob.Field_Senior_Email__c = rigProgram.Field_Senior__r.Email;
			endOfJob.Production_Coordinator_Email__c = rigProgram.Production_Coordinator__r.Email;
			endOfJob.Operations_Coordinator_Email__c = rigProgram.Operations_Coordinator__r.Email;
			endOfJob.Service_Rig_Coordinator_Email__c = rigProgram.Service_Rig_Coordinator__r.Email;
			endOfJob.Service_Rig_Planner_Email__c = rigProgram.Service_Rig_Planner__r.Email;
			System.debug('PopulateEOJEmailFieldsFromRigProgram->eoj: ' + endOfJob);
		}
	}
}